import { type EventSubscription, requireOptionalNativeModule } from 'expo-modules-core';

export type ExternalStorageKind = 'removable' | 'primary';

/**
 * App-specific external storage selected by Android. `root*` always points to
 * a writable app folder; `removable*` is populated only when a removable card
 * is currently mounted.
 */
export interface ExternalStorageInfo {
  available: boolean;
  kind?: ExternalStorageKind;
  label?: string;
  rootUri?: string;
  rootPath?: string;
  /** File URI for the volume root, useful for display/debugging. */
  volumeRootUri?: string;
  /** DocumentsUI URI used to open the SAF picker at this volume. */
  safRootUri?: string;
  removableRootUri?: string;
  removableRootPath?: string;
  removableSafRootUri?: string;
  /** Absolute root of the selected physical volume, e.g. /storage/0123-4567. */
  volumeRootPath?: string;
}

export interface NativeCommandResult {
  stdout: string;
  exit: number;
  timedOut: boolean;
  /** Absolute external directory used as this command's cwd. */
  cwd: string;
}

export type CopperRuntimeState =
  | 'bundle_missing'
  | 'not_installed'
  | 'ready'
  | 'repair_required'
  | 'package_mismatch';

/** How the verified runtime ZIP was staged into this particular APK. */
export type CopperRuntimeAssetStageMode =
  | 'none'
  | 'ci-validation'
  | 'device-candidate'
  | 'release'
  | 'unrecognized';

/** Native package/runtime state. A `bundle_missing` state intentionally means
 * this APK has no verified Copper-prefix bootstrap and cannot act as Termux. */
export interface CopperRuntimeStatus {
  state: CopperRuntimeState;
  ready: boolean;
  bundleAvailable: boolean;
  /** Provenance label generated by the verified Android asset stager. */
  assetStageMode: CopperRuntimeAssetStageMode;
  /** True for CI/private-device evidence APKs; never describe these as released runtime APKs. */
  candidateOnly: boolean;
  supportedAbi: string;
  runtimePrefix: string;
  runtimeHome: string;
  persistentBytes: number;
  quotaBytes: number;
  remainingBytes: number;
  /** Runtime executables and installed-package payload, excluding cache/index/tmp. */
  runtimePayloadBytes: number;
  /** Downloaded APT .deb archives that `apt clean` may reclaim. */
  aptArchiveBytes: number;
  /** Downloaded APT package indexes. */
  aptListsBytes: number;
  /** The runtime prefix's temporary directory. */
  runtimeTemporaryBytes: number;
  /** Persistent shell settings and user state under Copper's private $HOME. */
  shellHomeBytes: number;
  /** Copper installer metadata. */
  installerMetadataBytes: number;
  /** In-progress/retained installer staging directories, normally zero. */
  repairStagingBytes: number;
  freeDeviceBytes: number;
  packageName: string;
  expectedPackageName: string;
}

export interface CopperRuntimeSession {
  id: string;
  pid: number;
  /** Shared-storage cwd selected by the manual Terminal user. */
  cwd: string;
  startedAtEpochMs: number;
}

/** A short-lived diagnostic retained after a native PTY session exits. The
 * output tail is deliberately bounded and exists only to make a failed shell
 * launch actionable on the device that experienced it. */
export interface CopperRuntimeSessionExit {
  sessionId: string;
  exit: number;
  closedByUser: boolean;
  outputTail?: string;
  exitedAtEpochMs: number;
}

export type CopperRuntimeInstallStage = 'checking' | 'verifying' | 'extracting' | 'validating' | 'complete' | 'failed';

/** Native installation milestones. persistentBytes is live staging usage, not
 * a guessed percentage of a compressed archive. */
export interface CopperRuntimeInstallProgress {
  stage: CopperRuntimeInstallStage;
  message: string;
  persistentBytes: number;
  quotaBytes: number;
}

type CopperRuntimeEvents = {
  runtimeOutput: (event: { sessionId: string; data: string }) => void;
  runtimeExit: (event: CopperRuntimeSessionExit) => void;
  runtimeError: (event: { sessionId: string; message: string }) => void;
  runtimeInstallProgress: (event: CopperRuntimeInstallProgress) => void;
};

type NativeCopperExec = {
  addListener<EventName extends keyof CopperRuntimeEvents>(
    eventName: EventName,
    listener: CopperRuntimeEvents[EventName]
  ): EventSubscription;
  getStorageInfo(): Promise<ExternalStorageInfo>;
  getExternalFilesDir(): Promise<ExternalStorageInfo>;
  getExternalSdCard(): Promise<ExternalStorageInfo | null>;
  hasAllFilesAccess(): Promise<boolean>;
  requestAllFilesAccess(): Promise<boolean>;
  getTerminalStartDirectory(): Promise<string | null>;
  resolveSharedDirectory(target: string, workingDirectory: string | null): Promise<string>;
  getRuntimeStatus(): Promise<CopperRuntimeStatus>;
  installCopperRuntime(replaceExisting: boolean): Promise<CopperRuntimeStatus>;
  repairCopperRuntime(): Promise<CopperRuntimeStatus>;
  removeCopperRuntime(preserveHome: boolean): Promise<CopperRuntimeStatus>;
  startRuntimeSession(workingDirectory: string | null, rows: number, columns: number): Promise<CopperRuntimeSession>;
  writeRuntimeSession(sessionId: string, input: string): Promise<number>;
  resizeRuntimeSession(sessionId: string, rows: number, columns: number): Promise<boolean>;
  closeRuntimeSession(sessionId: string): Promise<boolean>;
  listRuntimeSessions(): Promise<CopperRuntimeSession[]>;
  getRuntimeSessionExitDetail(sessionId: string): Promise<CopperRuntimeSessionExit | null>;
  /** Shares an external file or user-granted SAF URI without a cache copy. */
  shareUri(uri: string, mimeType: string, title: string | null): Promise<boolean>;
  /** Runs a manual command anywhere in Android shared storage after user grant. */
  execAllFiles(command: string, workingDirectory: string | null, timeoutMs: number): Promise<NativeCommandResult>;
};

const native = requireOptionalNativeModule<NativeCopperExec>('CopperExec');

/**
 * Optional native bridge. It is included in a custom Copper Android build and
 * intentionally absent in Expo Go, iOS, and web.
 */
export const CopperExec = {
  isAvailable: (): boolean => native != null,

  getStorageInfo: async (): Promise<ExternalStorageInfo | null> =>
    native ? native.getStorageInfo() : null,

  getExternalFilesDir: async (): Promise<ExternalStorageInfo | null> =>
    native ? native.getExternalFilesDir() : null,

  getExternalSdCard: async (): Promise<ExternalStorageInfo | null> =>
    native ? native.getExternalSdCard() : null,

  hasAllFilesAccess: async (): Promise<boolean> => native ? native.hasAllFilesAccess() : false,

  requestAllFilesAccess: async (): Promise<boolean> => {
    if (!native) throw new Error('All-files access is available only in a Copper Android build.');
    return native.requestAllFilesAccess();
  },

  getTerminalStartDirectory: async (): Promise<string | null> =>
    native ? native.getTerminalStartDirectory() : null,

  resolveSharedDirectory: async (target: string, workingDirectory: string | null): Promise<string> => {
    if (!native) throw new Error('The manual terminal is available only in a Copper Android build.');
    return native.resolveSharedDirectory(target, workingDirectory);
  },

  getRuntimeStatus: async (): Promise<CopperRuntimeStatus | null> =>
    native ? native.getRuntimeStatus() : null,

  installCopperRuntime: async (replaceExisting = false): Promise<CopperRuntimeStatus> => {
    if (!native) throw new Error('Copper Runtime installation is available only in a Copper Android build.');
    return native.installCopperRuntime(replaceExisting);
  },

  repairCopperRuntime: async (): Promise<CopperRuntimeStatus> => {
    if (!native) throw new Error('Copper Runtime repair is available only in a Copper Android build.');
    return native.repairCopperRuntime();
  },

  removeCopperRuntime: async (preserveHome = false): Promise<CopperRuntimeStatus> => {
    if (!native) throw new Error('Copper Runtime removal is available only in a Copper Android build.');
    return native.removeCopperRuntime(preserveHome);
  },

  startRuntimeSession: async (workingDirectory: string | null, rows: number, columns: number): Promise<CopperRuntimeSession> => {
    if (!native) throw new Error('Copper Runtime sessions are available only in a Copper Android build.');
    return native.startRuntimeSession(workingDirectory, rows, columns);
  },

  writeRuntimeSession: async (sessionId: string, input: string): Promise<number> => {
    if (!native) throw new Error('Copper Runtime sessions are available only in a Copper Android build.');
    return native.writeRuntimeSession(sessionId, input);
  },

  resizeRuntimeSession: async (sessionId: string, rows: number, columns: number): Promise<boolean> => {
    if (!native) throw new Error('Copper Runtime sessions are available only in a Copper Android build.');
    return native.resizeRuntimeSession(sessionId, rows, columns);
  },

  closeRuntimeSession: async (sessionId: string): Promise<boolean> => {
    if (!native) return false;
    return native.closeRuntimeSession(sessionId);
  },

  listRuntimeSessions: async (): Promise<CopperRuntimeSession[]> =>
    native ? native.listRuntimeSessions() : [],

  getRuntimeSessionExitDetail: async (sessionId: string): Promise<CopperRuntimeSessionExit | null> =>
    native ? native.getRuntimeSessionExitDetail(sessionId) : null,

  addRuntimeOutputListener: (listener: CopperRuntimeEvents['runtimeOutput']): EventSubscription | null =>
    native?.addListener('runtimeOutput', listener) ?? null,

  addRuntimeExitListener: (listener: CopperRuntimeEvents['runtimeExit']): EventSubscription | null =>
    native?.addListener('runtimeExit', listener) ?? null,

  addRuntimeErrorListener: (listener: CopperRuntimeEvents['runtimeError']): EventSubscription | null =>
    native?.addListener('runtimeError', listener) ?? null,

  addRuntimeInstallProgressListener: (listener: CopperRuntimeEvents['runtimeInstallProgress']): EventSubscription | null =>
    native?.addListener('runtimeInstallProgress', listener) ?? null,

  shareUri: async (uri: string, mimeType: string, title: string | null): Promise<boolean> => {
    if (!native) throw new Error('Native sharing for an external/custom folder is unavailable in this build.');
    return native.shareUri(uri, mimeType, title);
  },

  execAllFiles: async (command: string, workingDirectory: string | null, timeoutMs: number): Promise<NativeCommandResult> => {
    if (!native) throw new Error('The manual terminal is available only in a Copper Android build.');
    return native.execAllFiles(command, workingDirectory, timeoutMs);
  },
};
